# -*- coding: utf-8 -*-
"""clinical_data_api.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13wuvaITfnf7qOJfLpe-RPA7TL9RZmyqz
"""

!pip install fastapi uvicorn pydantic pandas nest-asyncio

import pandas as pd
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from typing import Optional, List
import nest_asyncio
import uvicorn

# Initialise FastAPI app
app = FastAPI(title="Clinical Trial Data API", version="1.0.0")
github_url = "https://raw.githubusercontent.com/OrtensiaV/technical-interview-april-2026/refs/heads/main/question_5/adae.csv"

# Load the dataset (upload adae.csv to Colab first)
try:
    df = pd.read_csv(github_url)
    print(f"Dataset loaded successfully: {len(df)} records")
    print(f"Columns: {list(df.columns)}")
except Exception as e:
    print(f"Error loading dataset: {e}")
    df = pd.DataFrame()

# Endpoint 1: Welcome message
@app.get("/")
def read_root():
    return {"message": "Clinical Trial Data API is running"}

print("Testing GET / endpoint:")
result = read_root()
print(result)

from typing import Optional, List

# Define the request body structure unsing Pydantic
class AEQueryRequest(BaseModel):
  severity: Optional[List[str]] = None
  treatment_arm: Optional[str] = None

# Create the POST endpoint
@app.post("/ae-query")
def query_adverse_events(request: AEQueryRequest):
    """
    Filter adverse events based on severity and/or treatment arm.
    Returns count of matching records and list of unique subject IDs.
    """
    # Start with the full dataset
    filtered_df = df.copy()

    # Apply severity filter if provided
    if request.severity is not None and len(request.severity) > 0:
        # Filter for records matching any of the provided severities
        filtered_df = filtered_df[filtered_df['AESEV'].isin(request.severity)]

    # Apply treatment arm filter if provided
    if request.treatment_arm is not None:
        filtered_df = filtered_df[filtered_df['ACTARM'] == request.treatment_arm]

    # Get unique subject IDs
    unique_subjects = filtered_df['USUBJID'].unique().tolist()

    # Prepare response
    response = {
        "count": len(filtered_df),
        "unique_subjects": unique_subjects
    }

    return response

# Test the endpoint
# Test Case 1: Filter by severity and treatment arm
print("Test 1: Severity=['MILD', 'MODERATE'] and Treatment='Placebo'")
test_request_1 = AEQueryRequest(
    severity=["MILD", "MODERATE"],
    treatment_arm="Placebo"
)
result_1 = query_adverse_events(test_request_1)
print(f"Count: {result_1['count']}")
print(f"Number of unique subjects: {len(result_1['unique_subjects'])}")
print(f"First 5 subjects: {result_1['unique_subjects'][:5]}")
print()

# Test Case 2: Filter by severity only
print("Test 2: Severity=['SEVERE'] only")
test_request_2 = AEQueryRequest(severity=["SEVERE"])
result_2 = query_adverse_events(test_request_2)
print(f"Count: {result_2['count']}")
print(f"Number of unique subjects: {len(result_2['unique_subjects'])}")
print()

# Test Case 3: Filter by treatment arm only
print("Test 3: Treatment='Xanomeline High Dose' only")
test_request_3 = AEQueryRequest(treatment_arm="Xanomeline High Dose")
result_3 = query_adverse_events(test_request_3)
print(f"Count: {result_3['count']}")
print(f"Number of unique subjects: {len(result_3['unique_subjects'])}")
print()

# Test Case 4: No filters (should return all records)
print("Test 4: No filters")
test_request_4 = AEQueryRequest()
result_4 = query_adverse_events(test_request_4)
print(f"Count: {result_4['count']}")
print(f"Total unique subjects: {len(result_4['unique_subjects'])}")

# Create the risk score endpoint

@app.get("/subject-risk/{subject_id}")
def get_subject_risk(subject_id: str):
    """
    Calculate safety risk score for a specific subject based on adverse event severity.

    Scoring:
    - MILD: 1 point
    - MODERATE: 3 points
    - SEVERE: 5 points

    Risk Categories:
    - Low: Score < 5
    - Medium: 5 <= Score < 15
    - High: Score >= 15
    """
    # Filter data for the specific subject
    subject_data = df[df['USUBJID'] == subject_id]

    # Check if subject exists
    if subject_data.empty:
        raise HTTPException(
            status_code=404,
            detail=f"Subject ID '{subject_id}' not found in the dataset"
        )

    # Define severity weights
    severity_weights = {
        'MILD': 1,
        'MODERATE': 3,
        'SEVERE': 5
    }

    # Calculate risk score
    risk_score = 0
    for severity in subject_data['AESEV']:
        risk_score += severity_weights.get(severity, 0)

    # Determine risk category
    if risk_score < 5:
        risk_category = "Low"
    elif risk_score < 15:
        risk_category = "Medium"
    else:
        risk_category = "High"

    # Prepare response
    response = {
        "subject_id": subject_id,
        "risk_score": risk_score,
        "risk_category": risk_category
    }

    return response

# Test the endpoint

# Test Case 1: Example from the exercise (if this subject exists)
print("Test 1: Subject '01-701-1015'")
try:
    result_1 = get_subject_risk("01-701-1015")
    print(f"Subject ID: {result_1['subject_id']}")
    print(f"Risk Score: {result_1['risk_score']}")
    print(f"Risk Category: {result_1['risk_category']}")
except HTTPException as e:
    print(f"Error: {e.detail}")
print()

# Test Case 2: Find a valid subject from your data
print("Test 2: Using a valid subject from the dataset")
valid_subject = df['USUBJID'].iloc[0]  # Get first subject
result_2 = get_subject_risk(valid_subject)
print(f"Subject ID: {result_2['subject_id']}")
print(f"Risk Score: {result_2['risk_score']}")
print(f"Risk Category: {result_2['risk_category']}")
print()

# Test Case 3: Test error handling with invalid subject
print("Test 3: Invalid subject ID (should return 404)")
try:
    result_3 = get_subject_risk("INVALID-ID-999")
except HTTPException as e:
    print(f"Error caught successfully: {e.detail}")
print()

# Test Case 4: Analyse risk distribution across all subjects
print("Test 4: Risk distribution across all subjects")
all_subjects = df['USUBJID'].unique()
risk_distribution = {"Low": 0, "Medium": 0, "High": 0}

for subject in all_subjects[:10]:  # Test first 10 subjects
    result = get_subject_risk(subject)
    risk_distribution[result['risk_category']] += 1

print(f"Risk distribution (first 10 subjects):")
for category, count in risk_distribution.items():
    print(f"  {category}: {count}")

"""
Clinical Trial Data API
FastAPI application for querying and analysing clinical trial adverse event data.
"""

import pandas as pd
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from typing import Optional, List
import nest_asyncio
import uvicorn

# Allow nested event loops (required for Colab)
nest_asyncio.apply()

# ============================================================================
# DATA LOADING
# ============================================================================

# Load dataset from GitHub
github_url = "https://raw.githubusercontent.com/your-username/your-repo/main/adae.csv"

try:
    df = pd.read_csv(github_url)
    print(f"Dataset loaded successfully: {len(df)} records")
except Exception as e:
    print(f"Error loading dataset: {e}")
    df = pd.DataFrame()

# ============================================================================
# PYDANTIC MODELS
# ============================================================================

class AEQueryRequest(BaseModel):
    """Request model for adverse event filtering"""
    severity: Optional[List[str]] = None
    treatment_arm: Optional[str] = None

# ============================================================================
# FASTAPI APPLICATION
# ============================================================================

app = FastAPI(
    title="Clinical Trial Data API",
    description="API for querying and analysing clinical trial adverse event data",
    version="1.0.0"
)

# ============================================================================
# ENDPOINTS
# ============================================================================

@app.get("/")
def read_root():
    """Welcome endpoint"""
    return {"message": "Clinical Trial Data API is running"}


@app.post("/ae-query")
def query_adverse_events(request: AEQueryRequest):
    """
    Filter adverse events based on severity and/or treatment arm.

    Args:
        request: AEQueryRequest containing optional severity list and treatment_arm

    Returns:
        JSON with count of matching records and list of unique subject IDs
    """
    # Start with full dataset
    filtered_df = df.copy()

    # Apply severity filter if provided
    if request.severity is not None and len(request.severity) > 0:
        filtered_df = filtered_df[filtered_df['AESEV'].isin(request.severity)]

    # Apply treatment arm filter if provided
    if request.treatment_arm is not None:
        filtered_df = filtered_df[filtered_df['ACTARM'] == request.treatment_arm]

    # Get unique subject IDs
    unique_subjects = filtered_df['USUBJID'].unique().tolist()

    return {
        "count": len(filtered_df),
        "unique_subjects": unique_subjects
    }


@app.get("/subject-risk/{subject_id}")
def get_subject_risk(subject_id: str):
    """
    Calculate safety risk score for a specific subject.

    Scoring:
    - MILD: 1 point
    - MODERATE: 3 points
    - SEVERE: 5 points

    Risk Categories:
    - Low: Score < 5
    - Medium: 5 <= Score < 15
    - High: Score >= 15

    Args:
        subject_id: Unique subject identifier

    Returns:
        JSON with subject_id, risk_score, and risk_category

    Raises:
        HTTPException: 404 if subject_id not found
    """
    # Filter data for specific subject
    subject_data = df[df['USUBJID'] == subject_id]

    # Check if subject exists
    if subject_data.empty:
        raise HTTPException(
            status_code=404,
            detail=f"Subject ID '{subject_id}' not found in the dataset"
        )

    # Define severity weights
    severity_weights = {
        'MILD': 1,
        'MODERATE': 3,
        'SEVERE': 5
    }

    # Calculate risk score
    risk_score = 0
    for severity in subject_data['AESEV']:
        risk_score += severity_weights.get(severity, 0)

    # Determine risk category
    if risk_score < 5:
        risk_category = "Low"
    elif risk_score < 15:
        risk_category = "Medium"
    else:
        risk_category = "High"

    return {
        "subject_id": subject_id,
        "risk_score": risk_score,
        "risk_category": risk_category
    }

# ============================================================================
# SERVER STARTUP (for local execution)
# ============================================================================

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000, reload=True)